### ISSUE TITLE
quotient filter is missing auto_expand feature in init missing from docs and throws error

### ISSUE THREAD

**Issue by JSai23** [barrust/pyprobables#124]
<img width="938" alt="image" src="https://github.com/user-attachments/assets/27e72c5f-8572-41a4-8042-aa240dfc62af">

**Comment by barrust** [comment]
It exists on the latest, but that hasn't been released to pypi yet. For now, you would need to install it from source. I might be able to get it packaged out in the next few days.

**Comment by barrust** [comment]
I was hoping to get the remove/delete completed before the next version, but if a new version is needed, let me know.

**Comment by JSai23** [comment]
No its fine will just wait on the release just removed the arg for now. Thanks for the quick response.

**Comment by barrust** [comment]
Just pushed the new release: [v0.6.1](https://pypi.org/project/pyprobables/)
