### ISSUE TITLE
Update code to reflect end-of-life of Python 2 and 3.5

### ISSUE THREAD

**Issue by dekoza** [barrust/pyprobables#51]
How do you feel about modernizing the codebase? Py2 is no more and Py3.6 is the lowest supported version right now. I'm preparing Py3.8+ version on my fork if you're interested. The code can also be improved by using black+isort for formatting and incorporating typehints.

**Comment by barrust** [comment]
I would love to do this! I haven't been able to get much work on my projects done recently but hopefully I will be able to review your PR soon. I am hopeful that this isn't too large of a lift to remove both python 2.7 and 3.5. 

I am definitely interested in any work needed to get python 3.8 working!

**Comment by dekoza** [comment]
@barrust if you don't mind, I'll base the code on my previous PR.
