### ISSUE TITLE
Missing method to aggregate count-min sketches

### ISSUE THREAD

**Issue by racinmat** [barrust/pyprobables#61]
Count-min sketch has in theory property that 2 tables can be summed together which allows parallel count-min sketch building, but I don't see it implemented there.
Should I make pull request which implements it?

**Comment by barrust** [comment]
This is a great idea. I think this is an easy add for the base count-min-sketch but some thought will need to be taken for the `StreamThreshold` and `HeavyHitter` versions. 

For a `CMS` to be able to be merged the depth, width, and hashing function must all be the same. If there is an error in the definitions, I would assume some sort of exception should be thrown.

**Comment by racinmat** [comment]
I implemented that in my PR? but as mentioned there, I have a bit problem with comparing hash functions.
`StreamThreshold` and `HeavyHitter` raise `NotImplementedError` now.

**Comment by beviah** [comment]
any update on this? @racinmat i may be able to help. can you share your current code..

**Comment by racinmat** [comment]
Hi, sorry for the late answer, so far I have this https://github.com/barrust/pyprobables/pull/65
if you have any ideas or time how to help that would be great, thanks!
