### ISSUE TITLE
Add a function to insert raw `bytes` into a filter.

### ISSUE THREAD

**Issue by KOLANICH** [barrust/pyprobables#74]

**Comment by barrust** [comment]
I ***believe*** that this is possible with only putting in a different hashing function but to verify, could you provide a simple example of what you would like to do? 
Thanks!

**Comment by KOLANICH** [comment]
I mean that currently keys are `str`ings, but I need byte-strings. It is far more versatile (strings can always be converted to `bytes` with low overhead).

I have created (it is not yet finished and should not be used, large changes will likely happen) a tool https://github.com/KOLANICH-tools/DilatedHash.py that uses Bloom/Cuckoo filters on raw bytes.

**Comment by barrust** [comment]
I will have to do more testing on if a str object is required. In the code, I don't see a place where it is enforced but it has been awhile since I added a lot of functionality so I could be wrong.

**Comment by KOLANICH** [comment]
Thank you.
